### ISSUE TITLE
Work on better methods of sorting properties that are currently ignored?

### ISSUE THREAD

**Issue by laggingreflex** [jacobrask/eslint-plugin-sorting#19]
Lots of property types were added to ignore list recently because they were causing problems

    {
        ...a,
        [a()]: b,
        [a?b:c]: d,
        [a.b]: c,
        [a+b]: c
    }

There should ideally be better handling of these instead of ignoring.

**Comment by barm** [comment]
Added support for all of these cases (and more) except the spread operator in #21

**Comment by laggingreflex** [comment]
Awesome!

Spread operator I think should in fact be ignored, as it's often used to actually override previous properties.

**Comment by barm** [comment]
Yeah, I agree about the spread operator. Thanks!
