### ISSUE TITLE
Configuration for custom sorting or ignored properties

### ISSUE THREAD

**Issue by karlhorky** [jacobrask/eslint-plugin-sorting#22]
Sometimes I find myself wanting a specific (non-alphabetical) order in an object to ease parsing of the most important information. For instance, in redux action creators:

**profiles.js**

``` js
function receiveProfile (profile) {
  return {
    type: ADD_PROFILE, // <-- I like where this property is, but disabling and reenabling is a pain
    profile,
    receivedAt: Date.now()
  };
}
```

I know that I could disable the rule completely for the file or for the code block, but this is somewhat tedious.

One solution would be a configuration setting for a custom sort order, allowing exceptions at the start and at the end of the alphabetical sorting:

``` js
/* eslint sorting/sort-object-props: [ 1, { "customSortOrder": { "start": [ "type", "name" ], "end": [ "payload" ] } } ] */
```

In this example, if defined in the object's keys, `type` and `name` would need to come as first and second place in the object and `payload` would need come last.

---

Another idea I originally considered was a way to ignore properties from the sorting rules. This would probably be less useful though, and may lead to missed errors if applied globally:

``` js
/* eslint sorting/sort-object-props: [ 1, { "ignoredProps": [ "type" ] } ] */
```

---

Or if there's a better direction or another plugin that I've missed, I'm open to other ideas.

**Comment by jacobrask** [comment]
Another option would be a custom sort order, where `type` is specified to
always come first if it exists.

Den 28 juli 2016 18:00 skrev "Karl Horky" <notifications@github.com>:
>
> Sometimes I find myself wanting a specific (non-alphabetic) order in an
object to ease parsing of the most important information. For instance, in
redux reducers:
>
> profiles.js
>
> function receiveProfile (profile) { return { type: ADD_PROFILE, // <-- I
like where this property is, but disabling and reenabling is a pain
profile, receivedAt: Date.now() }; }
>
> I know that I could disable the rule completely for the file or for the
code block, but this is somewhat tedious.
>
> How would you feel about adding ignored properties to the configuration?
Maybe something like an ignored-props array?
>
> /* eslint sorting/sort-object-props: [ 1, { "ignoredProperties": [ "type"
] } ] */
>
> Or if there's a better direction or another plugin that I've missed, I'm
open to other ideas.

**Comment by karlhorky** [comment]
> a custom sort order

Cool idea, yeah I think this may be better. Kind of like a priority system for the properties.

**Comment by karlhorky** [comment]
I've updated the issue with a simple custom sort order configuration proposal.
